language: go

go:
- master

branches:
  only:
  - master
notifications:
  slack:
    secure: L404O7JkR23ee7OnA0tojsmk0mxa283ZNFLikeYB9xx85mM1Ifn0NWaDKaBC7sLJeVrmM+b14LkmFNlCJ5lQXocwvl1uH2yNif4wOrdZV/4zD/vEcmDqvaFh0z5jhBzXXs+n3quSOaMa3yYB66mgx5NbR+jBjmq1z70Le0d0/ldErDnyhkmgHZHUjxFoRGdGVCYrm9ObsaJ1iBiM10unvcOD/sKo5Ha7QF3cRtDvtsUfDPoHNQWDCsSR+hRs3RZgvx9RkVH/PE75EDB/pfOy8c/h9Hv6/VsySvk74AiyjfeOppAQiZuNezz4JedXDhZrnEdJMgBN3X0lOySZ8zpOplTngd/B4plx7LE9Az4WJkzhHjSuNYQZZslDprjK32sr63lucRepePY2QLauxfLI+6om3ttuFZE92ZcpTf9qCK+Ao3slNoikHDbZpJl8C8sM2MlK7nrlV5lwbH6r3zIsLg5Pnlztl2pX+dfGVBU4rWBwwKfSa0hdcbQW6S9r5SA0b6JtjCByClxMR8nukAHT4EbBIqDgdaZY9hmp5kOtvjb384pwZIOp/vzfpp+YYIh0hLkE+qYN9wtclUFNFDpXEMOUIrHbnVbCXFgtOg4gPNUVJYAM4n/bZvRSddt9sRnLK51Pp0uZMw9Aibyjt80nK+FzdUMIv517BrXrmSaY2EQ=
