language: go
go:
- master
branches:
  only:
  - master
notifications:
  slack:
    secure: YWwmHTWsY6LgJgSW4BXxXk1fay0atem4Kq9lTMhyuXY9a9BkU93wmcIfbHuMQk9JhhvRpGBViuaXUdXBd397X4/Wi/2rYSLldkSKluqR8dwf1FmKfIh6buTXIBZvKP4TCJI0kqPzFfDCrNj1htk80m3YwG2t3NoII/iAshu0SpqfkEYHHW515QARok2sTgPNH1gjt6CDl9DAlHgDXGkzUV78GAb/RTHk9ZYeFOceFvLefrBELlNzwQBDjbGJJ0XVHrSoCj6zyyR4Wb9k4VvrEKxLsJVcqwYkXCFWGubmCuFFBhUTp/W3tnum08lhYpmQ++up2TPX46CW/dqLX0hWCLNr8ZZxhXtDHG8HIzxM3AcMg2Gn5U1lsVFIIzW5nhBg/IWhafo6bEP2iTYyhq1vLW4HvSfplpdb1OvolxQlwFMU484/n15L3Ex+4H63tF8COEqqu8rDmQBjxwP9Ko/EAlN9GvHIxKrEBKNvsVJr8TDi8chauRax+JZg/LnZFmGIlR3ela6el9JC6UottBzG8fqIfYWstS1VbpqUz6jpeRc1N/xR2ArvjGghm5xGqtWx5wZTJHhLG5vhsFPi+G0lMwm2vfvFn5UO39T1D7iMd97O7T5X+Ry3rXMvdiD8Zt441fjahwY39hAVS8Jf2lTE2515eJOCjM+8c4DoYjKnNSs=
